project:
  type: website
  output-dir: docs

website:
  title: "Welcome"
  navbar:
    title: false
    logo: images/logo.png
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: Portfolio.qmd
      - href: Blog.qmd
  page-footer:
    background: light
    right: © 2025 Whitney Airewele. All rights reserved


format:
  html:
    theme: 
      - lux
      - brand
      - styles.scss
    mainfont: Urbanist
    toc-title: "On this page"
    toc-location: right
    page-layout: article
    
    

    
    




