project:
  type: website
  output-dir: docs

website:
  title: "Welcome"
  navbar:
    title: false
    logo: images/logo.png
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - hello.qmd
page-footer:
  background: light
  right: © 2025 Whitney Airewele. All rights reserved


format:
  html:
    theme: 
      - lux
      - brand
      - styles.scss
    mainfont: Urbanist
    toc: true
    toc-title: "A LITTLE ABOUT ME"
    toc-location: right
    toc-depth: 1

    
    




